import colors from 'tailwindcss/colors'
import {
    atomOneDark,
    atomOneDarkReasonable,
    atomOneLight,
    vs,
    vs2015,
} from 'react-syntax-highlighter/dist/cjs/styles/hljs'

export const darkTheme = {
    ...atomOneDark,
    // 'hljs-string': { color: colors.green[400] },
    // // 'hljs-attr': { color: atomOneDark['hljs-attr'] },
    // 'hljs-attr': { color: colors.orange[300] },
    // 'hljs-attribute': { color: atomOneDark['hljs-attribute'] },
    // 'hljs-built_in': { color: atomOneDark['hljs-built_in'] },
    // 'hljs-bullet': { color: atomOneDark['hljs-bullet'] },
    // 'hljs-class .hljs-title': { color: atomOneDark['hljs-class .hljs-title'] },
    // // 'hljs-comment': { color: '#5c6370', fontStyle: atomOneDark['hljs-comment': { color: '#5] },
    // 'hljs-deletion': { color: atomOneDark['hljs-deletion'] },
    // 'hljs-doctag': { color: atomOneDark['hljs-doctag'] },
    // 'hljs-emphasis': { fontStyle: 'italic' },
    // 'hljs-formula': { color: atomOneDark['hljs-formula'] },
    // 'hljs-keyword': { color: atomOneDark['hljs-keyword'] },
    // // 'hljs-link': { color: '#61aeee', textDecoration: atomOneDark['hljs-link': { color: '#6] },
    // // 'hljs-literal': { color: atomOneDark['hljs-literal'] },
    // 'hljs-literal': { color: colors.white },
    // 'hljs-meta': { color: atomOneDark['hljs-meta'] },
    // 'hljs-meta-string': { color: atomOneDark['hljs-meta-string'] },
    // // 'hljs-name': { color: atomOneDark['hljs-name'] },
    // 'hljs-number': { color: atomOneDark['hljs-number'] },
    // // 'hljs-quote': { color: '#5c6370', fontStyle: atomOneDark['hljs-quote': { color: '#5] },
    // 'hljs-regexp': { color: atomOneDark['hljs-regexp'] },
    // 'hljs-section': { color: atomOneDark['hljs-section'] },
    // 'hljs-selector-attr': { color: atomOneDark['hljs-selector-attr'] },
    // 'hljs-selector-class': { color: atomOneDark['hljs-selector-class'] },
    // 'hljs-selector-id': { color: atomOneDark['hljs-selector-id'] },
    // 'hljs-selector-pseudo': { color: atomOneDark['hljs-selector-pseudo'] },
    // 'hljs-selector-tag': { color: atomOneDark['hljs-selector-tag'] },
    // 'hljs-strong': { fontWeight: 'bold' },
    // 'hljs-subst': { color: atomOneDark['hljs-subst'] },
    // 'hljs-symbol': { color: atomOneDark['hljs-symbol'] },
    // 'hljs-template-variable': { color: atomOneDark['hljs-template-variable'] },
    // 'hljs-title': { color: atomOneDark['hljs-title'] },
    // 'hljs-type': { color: atomOneDark['hljs-type'] },
    // 'hljs-variable': { color: atomOneDark['hljs-variable'] },
}
